ALTER TABLE resultats
    ADD COLUMN IF NOT EXISTS q1_time INT NULL AFTER time,
    ADD COLUMN IF NOT EXISTS q2_time INT NULL AFTER q1_time,
    ADD COLUMN IF NOT EXISTS q3_time INT NULL AFTER q2_time,
    ADD COLUMN IF NOT EXISTS sq1_time INT NULL AFTER q3_time,
    ADD COLUMN IF NOT EXISTS sq2_time INT NULL AFTER sq1_time,
    ADD COLUMN IF NOT EXISTS sq3_time INT NULL AFTER sq2_time;